import Head from 'next/head'
import { view, readfile } from '@/lib/api'
import Typography from '@mui/material/Typography'
import Header from '@/components/Header'
import BasicInfo from '@/components/BasicInfo'
import Directory from '@/components/Directory'
import FileView from '@/components/FileView'

export async function getServerSideProps(context) {
  const path = "/" + (context?.query?.path || []).join("/")
  let l = await view(path)

  if (l.filetype === "code" || l.filetype === "text") {
    const f = await readfile(path);
    l.context = f;
  }
  return { props: l }
}

export default function Home(props) {
  let mainView = <></>;
  if (!props.found) {
    mainView = <Typography variant="h4" sx={{ m: 2 }}>File Not Found</Typography>
  } else {
    if (props.isDir) {
      mainView = <Directory {...props} />
    } else if (props.isFile) {
      mainView = <FileView {...props} />
    }
  }

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=0.8,minimum-scale=0.8, maximum-scale=1.0" />
        <title>{"DAV  " + props.path}</title>
        <link href="https://vjs.zencdn.net/7.15.4/video-js.css" rel="stylesheet" />
      </Head>
      <Header />
      <BasicInfo path={props.path} is_trash={props.is_trash} />
      {mainView}
    </>
  )
}
